### ISSUE TITLE
weight release

### ISSUE THREAD

**Issue by zwhus** [jshilong/GPT4RoI#1]
What an amazing job, and thanks for your contributions to the open source community, I'd like to try out some new ideas by using model weights, so do you have any plans to release weights anytime soon?

**Comment by jshilong** [comment]
Because I just changed the place of work, everything has not been set up yet, because it is going to be converted to llama diff, I will release it as asap

**Comment by zwhus** [comment]
Thank you for your reply and I will look forward to the publication of the weights！

**Comment by jshilong** [comment]
> Thank you for your reply and I will look forward to the publication of the weights！

Sorry for the delay. I have released the weights and you can try them now.
