### ISSUE TITLE
The main modifications in comparison with the native MMCV1.4.7 and MMDet ?

### ISSUE THREAD

**Issue by yingfei1016** [jshilong/GPT4RoI#2]
Hi，
    I've observed that this code comes with built-in MMCV1.4.7 and MMDet. However, the native mmdet and mmcv may more convenient to use. So, could you delineate the main modifications in comparison with the native MMCV1.4.7 and MMDet?

**Comment by jshilong** [comment]
You can ignore mmdet because it is pure Python. If you want to use the official variant of MMCV1.4.7, it should be possible as mmcv has not been modified.

**Comment by yingfei1016** [comment]
Thank you very much!

**Comment by hsb1995** [comment]
![image](https://github.com/jshilong/GPT4RoI/assets/149936473/b9a07d9e-12f0-4af6-bc79-bc56693e0650)
Whether I download the official version or the mmcv full provided by your company, this error is reported
