### ISSUE TITLE
ValueError: The following `model_kwargs` are not used by the model: ['images']

### ISSUE THREAD

**Issue by anex004** [jshilong/GPT4RoI#21]
Hi @jshilong great work considering ROI for language models.

I am getting this error "ValueError: The following `model_kwargs` are not used by the model: ['images']" while trying the inference code. Probably because 'images' is not considered as a parameter to the model.generate function.

with torch.amp.autocast(device_type='cuda'):
                output_ids = self.model.generate(
                    input_ids,
                    images=image.unsqueeze(0).half().cuda(),
                    do_sample=True,
                    temperature=0.2,
                    max_new_tokens=1024,
                    stopping_criteria=[stopping_criteria])

Could you please confirm if you are using any specific version of the 'torch', 'llava', or 'transformers' library?  
Thank you!

**Comment by jshilong** [comment]
Hi, just delete that line that validates the model_kwargs, I will fix this check ASAP

**Comment by anex004** [comment]
Thanks @jshilong for the prompt response! just did that and it worked.
