### ISSUE TITLE
train_stage1.sh and train_stage2.sh 

### ISSUE THREAD

**Issue by ShramanPramanick** [jshilong/GPT4RoI#3]
Hi, Currently the two bash scripts look similar. Can you please confirm the commands for the 1st and 2nd stage of training? I noticed that the data loading is being controlled from config. How exactly the model is properly frozen in two separate stages?

**Comment by jshilong** [comment]
Thank you for your interest！
'export ONLY_SPI=1' in the first stage can ensure that the model components are correctly frozen

**Comment by jshilong** [comment]
If you have any further questions, please don't hesitate to reach out to me

**Comment by ShramanPramanick** [comment]
Thanks for your explanation. It is clear to me now.
