### ISSUE TITLE
Question about Table 4

### ISSUE THREAD

**Issue by HenryHZY** [jshilong/GPT4RoI#32]
Hi, @jshilong @PeizeSun @ShoufaChen
I would like to ask some questions about "Table 4: Compariation of region caption ability on the validation dataset on Visual Genome".

1. Do you divide the validation dataset for VG region caption task by yourselves?
In the original VG dataset, it seems that there is no validation split. 
Could you please provide a link or a README to the validation dataset with me?

2. Do you reproduce the result of GRiT?
In GRiT's paper, it also seems that there is no related experimental result (e.g., CIDEr for the validation dataset for VG region captioning). 
Could you provide more details about this experiment?

Thank you in advance.

**Comment by jshilong** [comment]
About the Validation set, https://github.com/JialianW/GRiT/blob/master/datasets/DATASETS.md
For the results of GRiT, you can refer to the paper  https://arxiv.org/abs/2308.01907

**Comment by HenryHZY** [comment]
Thanks for your quick reply!
