### ISSUE TITLE
Dataset for stage 2

### ISSUE THREAD

**Issue by sysoda** [jshilong/GPT4RoI#4]
Hello, thank you very much for your excellent work. However, I have some doubts about the dataset, and I would appreciate it if you could clarify them for me. Where can I download the train.json file for visual_genome? Do I need to run EVA-02-DET myself to obtain the llava_150k_bbox_pred_results.pkl file?

**Comment by jshilong** [comment]
Sorry for the late response
For visual_genome, i download it from [opendatalab](https://opendatalab.com/)
I upload llava_150k_bbox_pred_results.pkl here https://huggingface.co/shilongz/temp/tree/main

**Comment by sysoda** [comment]
Thank you for your help!

**Comment by IceIce1ce** [comment]
Hi @sysoda, Can you share your train.json file?
