### ISSUE TITLE
Retraining issue

### ISSUE THREAD

**Issue by anonymo-user** [jshilong/GPT4RoI#5]
Hi,

I appreciate the effort you put into your framework, but I encountered some confusion while attempting to retrain it. The guidance suggests using the original LLaMA weights for training, but I noticed in your script that the model name input is set as `vicuna-7b`: `/mnt/petrelfs/share_data/zhangshilong/vicuna-7b/`.

I attempted to use both the **original** LLaMA and LLaVA huggingface format (haven't applied your delta since it haven't been released yet), but it always resulted in this error:

```
  File "/gpt4roi/gpt4roi/train/train_mem.py", line 16, in <module>
    train()
  File "/gpt4roi/gpt4roi/train/train.py", line 641, in train
    model.initialize_vision_tokenizer(mm_use_im_start_end=model_args.mm_use_im_start_end,
  File "/gpt4roi/gpt4roi/models/spi_llava.py", line 295, in initialize_vision_tokenizer
    raise ValueError(
ValueError: Unexpected embed_tokens_weight shape. Pretrained: torch.Size([2, 4096]). Current: torch.Size([32006, 4096]). Numer of new tokens: 0.
```

I would appreciate your guidance in resolving the error and making the code runnable. Could you please provide me with the necessary steps or adjustments to address the issue?

**Comment by jshilong** [comment]
1. The guidance suggests using the original LLaMA weights for training. 
However, I apologize for any confusion caused. What I actually adapted is Vicuna-7B, an instruction-turned-model based on LLaMA. You can refer to the model's page on Hugging Face ([https://huggingface.co/AlekseyKorshuk/vicuna-7b) ↗](https://huggingface.co/AlekseyKorshuk/vicuna-7b)) or obtain it from the LLaVA repository.

**Comment by jshilong** [comment]
I will polish the README and release the weights this week. I will also check the error you mentioned.

**Comment by jshilong** [comment]
After reviewing the code, I discovered that switching to Vicuna may resolve the error.

**Comment by jshilong** [comment]
I have published the checkpoint and polished the README today, so you can now pull them and use this repository more smoothly.

**Comment by jshilong** [comment]
> Hi, I believe that the incorrect weight belongs to the LLaVA pretrained projectors: https://github.com/jshilong/GPT4RoI/blob/main/gpt4roi/models/spi_llava.py#L284-L287
> 
> Do you have any idea what the correct projector is?

I have polished the README, especially on how to prepare data and checkpoints to launch the training. You can now pull the repository.
Please feel free to reach out to me again if you encounter any further issues.
