### ISSUE TITLE
n-round chat fails on the demo

### ISSUE THREAD

**Issue by likanchuan** [jshilong/GPT4RoI#6]
The chatbot works well according to the given region when I ask the first question. But for the second ask it keeps processing and never generates a sentence. It may be an issue to be fixed.

**Comment by jshilong** [comment]
It could be that the server is experiencing some instability, but I just tested it and didn't encounter any issues. Would you mind trying again and seeing if the problem persists? If it does, please feel free to provide me with an example, and I'll be happy to debug it for you.
